[project]
name = "razorpay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Purvika Reddy", email = "purvika.reddymk@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.20.0",
    "pandas>=3.0.5",
    "streamlit",
    "python-dotenv>=1.2.3",
]

[project.scripts]
razorpay = "razorpay:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
